// This file was generated by MikroORM CLI. Do not edit manually.
// Re-run `mikro-orm discovery:export` to update.

import { BoardMemberSchema } from '../modules/domain/board/board-member/entities/board-member.entity';
import { BoardSchema } from '../modules/domain/board/entities/board.entity';
import { CardCommentSchema } from '../modules/domain/card/card-comment/entities/card-comment.entity';
import { CardHistorySchema } from '../modules/domain/card/card-history/entities/card-history.entity';
import { CardSchema } from '../modules/domain/card/entities/card.entity';
import { CardTagSchema } from '../modules/domain/card/entities/card-tag.entity';
import { ColumnSchema } from '../modules/domain/column/entities/column.entity';
import { NotificationSchema } from '../modules/domain/notification/entities/notification.entity';
import { TagSchema } from '../modules/domain/tag/entities/tag.entity';
import { UserSchema } from '../modules/auth/user/entities/user.entity';
import { UserSessionSchema } from '../modules/auth/user-session/entities/user-session.entity';
import { type Constructor, EntityManager as DriverEntityManager } from '@mikro-orm/postgresql';

export const entities = [
  BoardMemberSchema,
  BoardSchema,
  CardCommentSchema,
  CardHistorySchema,
  CardSchema,
  CardTagSchema,
  ColumnSchema,
  NotificationSchema,
  TagSchema,
  UserSchema,
  UserSessionSchema,
] as const;

export type Database = typeof entities;

export type EntityManager = DriverEntityManager & { '~entities': Database };
export const EntityManager = DriverEntityManager as Constructor<EntityManager>;
